import type { RouteRecordRaw } from 'vue-router'

export const asyncRoutes: RouteRecordRaw[] = [
  {
    path: '/',
    children: [
      {
        path: 'dashboard',
        name: 'Dashboard',
        meta: { title: '仪表盘', icon: 'DashboardOutlined', sort: 1 },
        redirect: '/dashboard/workspace',
        children: [
          { path: 'workspace', name: 'DashboardWorkspace', meta: { title: '个人工作台' }, component: () => import('@/views/dashboard/workspace/WorkspaceView.vue') },
          { path: 'overview', name: 'DashboardOverview', meta: { title: '系统总览' }, component: () => import('@/views/dashboard/Overview.vue') },
          { path: 'model', name: 'ModelDashboard', meta: { title: '模型看板' }, component: () => import('@/views/dashboard/ModelDashboard.vue') },
          { path: 'data', name: 'DataDashboard', meta: { title: '数据看板' }, component: () => import('@/views/dashboard/DataDashboard.vue') },
        ],
      },
      {
        path: 'model',
        name: 'Model',
        meta: { title: '模型管理', icon: 'ExperimentOutlined', sort: 2, permission: 'model' },
        redirect: '/model/list',
        children: [
          { path: 'list', name: 'ModelList', meta: { title: '模型列表', permission: 'model' }, component: () => import('@/views/model/ModelList.vue') },
          { path: ':id', name: 'ModelDetail', meta: { title: '模型详情', hidden: true }, component: () => import('@/views/model/ModelDetail.vue') },
          { path: 'evaluations', name: 'EvalList', meta: { title: '评估管理' }, component: () => import('@/views/model/EvalList.vue') },
          { path: 'evaluations/:id', name: 'EvalDetail', meta: { title: '评估详情', hidden: true }, component: () => import('@/views/model/EvalDetail.vue') },
          { path: 'approvals', name: 'ApprovalList', meta: { title: '审批管理' }, component: () => import('@/views/model/ApprovalList.vue') },
          { path: 'deployments', name: 'DeploymentList', meta: { title: '部署管理' }, component: () => import('@/views/model/DeploymentList.vue') },
          { path: 'deployments/:id', name: 'DeploymentDetail', meta: { title: '部署详情', hidden: true }, component: () => import('@/views/model/DeploymentDetail.vue') },
          { path: 'routes', name: 'RouteConfig', meta: { title: '流量路由' }, component: () => import('@/views/model/RouteConfig.vue') },
          { path: 'versions', name: 'VersionList', meta: { title: '版本管理' }, component: () => import('@/views/model/VersionList.vue') },
          { path: 'inference-logs', name: 'InferenceLog', meta: { title: '推理日志' }, component: () => import('@/views/model/InferenceLog.vue') },
        ],
      },
      {
        path: 'data',
        name: 'Data',
        meta: { title: '数据管理', icon: 'DatabaseOutlined', sort: 3, permission: 'data' },
        redirect: '/data/cdr/patients',
        children: [
          { path: 'cdr/search', name: 'ClinicalSearch', meta: { title: '临床检索' }, component: () => import('@/views/data-cdr/ClinicalSearch.vue') },
          { path: 'cdr/disease', name: 'DiseaseList', meta: { title: '专病管理' }, component: () => import('@/views/data-cdr/DiseaseList.vue') },
          { path: 'cdr/disease/:id', name: 'DiseaseDetail', meta: { title: '专病详情', hidden: true }, component: () => import('@/views/data-cdr/DiseaseDetail.vue') },
          { path: 'cdr/patients', name: 'PatientList', meta: { title: '患者管理' }, component: () => import('@/views/data-cdr/PatientList.vue') },
          { path: 'cdr/patients/:id', name: 'PatientDetail', meta: { title: '患者详情', hidden: true }, component: () => import('@/views/data-cdr/PatientDetail.vue') },
          { path: 'cdr/patients/:id/encounters/:encounterId', name: 'EncounterDetail', meta: { title: '就诊详情', hidden: true }, component: () => import('@/views/data-cdr/EncounterDetail.vue') },
          { path: 'cdr/quality-rules', name: 'QualityRuleList', meta: { title: '质量规则' }, component: () => import('@/views/data-cdr/QualityRuleList.vue') },
          { path: 'cdr/quality-results', name: 'QualityResultList', meta: { title: '质量检测' }, component: () => import('@/views/data-cdr/QualityResultList.vue') },
          { path: 'rdr/projects', name: 'ProjectList', meta: { title: '研究项目' }, component: () => import('@/views/data-rdr/ProjectList.vue') },
          { path: 'rdr/datasets', name: 'DatasetList', meta: { title: '数据集' }, component: () => import('@/views/data-rdr/DatasetList.vue') },
        ],
      },
      {
        path: 'etl',
        name: 'Etl',
        meta: { title: '数据转换', icon: 'SwapOutlined', sort: 4, permission: 'data' },
        redirect: '/etl/pipelines',
        children: [
          { path: 'datasources', name: 'DataSourceList', meta: { title: '数据源管理' }, component: () => import('@/views/data-cdr/DataSourceList.vue') },
          { path: 'datasources/:id', name: 'DataSourceDetail', meta: { title: '数据源详情', hidden: true }, component: () => import('@/views/data-cdr/DataSourceDetail.vue') },
          { path: 'pipelines', name: 'EtlPipelineList', meta: { title: '管道管理' }, component: () => import('@/views/data-etl/EtlPipelineList.vue') },
          { path: 'pipelines/:id', name: 'EtlPipelineConfig', meta: { title: '管道配置', hidden: true }, component: () => import('@/views/data-etl/EtlPipelineConfig.vue') },
          { path: 'executions', name: 'EtlExecutionList', meta: { title: '执行监控' }, component: () => import('@/views/data-etl/EtlExecutionList.vue') },
          { path: 'sync', name: 'SyncTaskList', meta: { title: '数据同步' }, component: () => import('@/views/data-cdr/SyncTaskList.vue') },
          { path: 'schedule', name: 'ScheduleTaskList', meta: { title: '定时任务' }, component: () => import('@/views/schedule/TaskList.vue') },
        ],
      },
      {
        path: 'label',
        name: 'Label',
        meta: { title: '标注管理', icon: 'EditOutlined', sort: 5, permission: 'label' },
        redirect: '/label/tasks',
        children: [
          { path: 'tasks', name: 'LabelTaskList', meta: { title: '标注任务' }, component: () => import('@/views/label/LabelTaskList.vue') },
          { path: 'workspace/:id', name: 'LabelWorkspace', meta: { title: '标注工作台', hidden: true }, component: () => import('@/views/label/LabelWorkspace.vue') },
          { path: 'detail/:id', name: 'LabelTaskDetail', meta: { title: '标注详情', hidden: true }, component: () => import('@/views/label/LabelTaskDetail.vue') },
        ],
      },
      {
        path: 'alert',
        name: 'Alert',
        meta: { title: '告警中心', icon: 'AlertOutlined', sort: 7 },
        children: [
          { path: 'active', name: 'AlertList', meta: { title: '活跃告警' }, component: () => import('@/views/alert/AlertList.vue') },
          { path: 'rules', name: 'AlertRuleList', meta: { title: '告警规则' }, component: () => import('@/views/alert/AlertRuleList.vue') },
          { path: 'detail/:id', name: 'AlertDetail', meta: { title: '告警详情', hidden: true }, component: () => import('@/views/alert/AlertDetail.vue') },
        ],
      },
      {
        path: 'audit',
        name: 'Audit',
        meta: { title: '审计日志', icon: 'FileSearchOutlined', sort: 8, permission: 'audit' },
        children: [
          { path: 'operations', name: 'OperationLog', meta: { title: '操作审计' }, component: () => import('@/views/audit/OperationLog.vue') },
          { path: 'data-access', name: 'DataAccessLog', meta: { title: '数据访问' }, component: () => import('@/views/audit/DataAccessLog.vue') },
          { path: 'system-events', name: 'SystemEventLog', meta: { title: '系统事件' }, component: () => import('@/views/audit/SystemEventLog.vue') },
          { path: 'compliance', name: 'ComplianceReport', meta: { title: '合规报表' }, component: () => import('@/views/audit/ComplianceReport.vue') },
        ],
      },
      {
        path: 'message',
        name: 'Message',
        meta: { title: '消息中心', icon: 'BellOutlined', sort: 9 },
        children: [
          { path: 'list', name: 'MessageList', meta: { title: '我的消息' }, component: () => import('@/views/message/MessageList.vue') },
          { path: 'detail/:id', name: 'MessageDetail', meta: { title: '消息详情', hidden: true }, component: () => import('@/views/message/MessageDetail.vue') },
          { path: 'settings', name: 'NotificationSettings', meta: { title: '通知设置' }, component: () => import('@/views/message/NotificationSettings.vue') },
          { path: 'templates', name: 'TemplateManagement', meta: { title: '模板管理' }, component: () => import('@/views/message/TemplateManagement.vue') },
        ],
      },
      {
        path: 'system',
        name: 'System',
        meta: { title: '系统设置', icon: 'SettingOutlined', sort: 6 },
        redirect: '/system/code-systems',
        children: [
          {
            path: 'masterdata',
            name: 'SystemMasterData',
            meta: { title: '主数据配置' },
            redirect: '/system/code-systems',
            children: [
              { path: 'code-systems', name: 'CodeSystems', meta: { title: '编码体系' }, component: () => import('@/views/masterdata/CodeSystems.vue') },
              { path: 'mappings', name: 'MappingManager', meta: { title: '编码映射' }, component: () => import('@/views/masterdata/MappingManager.vue') },
              { path: 'clinical-rules', name: 'ClinicalRules', meta: { title: '临床规则' }, component: () => import('@/views/masterdata/ClinicalRules.vue') },
              { path: 'domains', name: 'DomainManager', meta: { title: '领域管理' }, component: () => import('@/views/masterdata/DomainManager.vue') },
              { path: 'institutions', name: 'InstitutionList', meta: { title: '机构管理' }, component: () => import('@/views/masterdata/InstitutionList.vue') },
              { path: 'knowledge', name: 'KnowledgeList', meta: { title: '知识体系' }, component: () => import('@/views/masterdata/KnowledgeList.vue') },
              { path: 'data-elements', name: 'DataElementList', meta: { title: '数据元管理' }, component: () => import('@/views/masterdata/DataElementList.vue') },
            ],
          },
          {
            path: 'sys',
            name: 'SystemAdmin',
            meta: { title: '系统管理' },
            redirect: '/system/users',
            children: [
              { path: 'users', name: 'UserList', meta: { title: '用户管理' }, component: () => import('@/views/system/UserList.vue') },
              { path: 'users/:id', name: 'UserDetail', meta: { title: '用户详情', hidden: true }, component: () => import('@/views/system/UserDetail.vue') },
              { path: 'roles', name: 'RoleList', meta: { title: '角色管理' }, component: () => import('@/views/system/RoleList.vue') },
              { path: 'roles/:id', name: 'RoleDetail', meta: { title: '角色详情', hidden: true }, component: () => import('@/views/system/RoleDetail.vue') },
              { path: 'permissions', name: 'PermissionManagement', meta: { title: '权限管理' }, component: () => import('@/views/system/PermissionManagement.vue') },
              { path: 'config', name: 'SystemConfig', meta: { title: '系统参数' }, component: () => import('@/views/system/SystemConfig.vue') },
              { path: 'desensitize', name: 'DesensitizeRule', meta: { title: '脱敏规则' }, component: () => import('@/views/data-cdr/DesensitizeRule.vue') },
            ],
          },
        ],
      },
    ],
  },
]
