input {
  tcp {
    port => 5044
    codec => json_lines
  }
}

filter {
  if [traceId] {
    mutate {
      add_field => { "trace_id" => "%{traceId}" }
    }
  }

  # Parse timestamp
  date {
    match => ["timestamp", "ISO8601"]
    target => "@timestamp"
  }

  # Add index date for daily rotation
  ruby {
    code => "event.set('index_date', event.get('@timestamp').time.strftime('%Y.%m.%d'))"
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "maidc-log-%{index_date}"
  }
}
