server:
  port: 8082

spring:
  application:
    name: maidc-data
  datasource:
    url: jdbc:postgresql://localhost:5432/maidc?currentSchema=cdr&stringtype=unspecified
    username: maidc
    password: maidc123
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        default_schema: cdr
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: localhost
      port: 6379
      password: maidc_redis
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
      config:
        import-check:
          enabled: false

maidc:
  jwt:
    secret: maidc-jwt-secret-key-2026-change-in-production
  etl:
    csv-base-dir: E:/pxg_project/data/icu-datasets
    parallel: 3
    db-url: jdbc:postgresql://localhost:5432/maidc
    db-schema: ods
    db-user: maidc
    db-password: maidc123
    ddl-path: E:/pxg_project/docker/init-db

logging:
  level:
    com.maidc: INFO
