server:
  port: 8084

spring:
  application:
    name: maidc-task
  datasource:
    url: jdbc:postgresql://localhost:5432/maidc?currentSchema=system&stringtype=unspecified
    username: maidc
    password: maidc123
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        default_schema: system
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: localhost
      port: 6379
      password: maidc_redis
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
      config:
        import-check:
          enabled: false

logging:
  level:
    com.maidc: INFO
